# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4628f9092bab4df53cbc84e29527c5dcfdee37475bb46ebaa94967211db7adbf70c6877beae4da253f338076f4b4ef1ad15e20d3881adecb59e5fdba199999fb

test:
  secret_key_base: 90068e9109cb0f4803c780a5052113ae8b1ba1cb4a5c396fa64db9c2b5e642d8f0d4f2ebeb40d66151e362d64f5f54ddb0c7b1953eee26297d2483fa73e5894b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
